language: r
sudo: false
r:
  - release
  - devel
repos:
  CRAN: https://cloud.r-project.org
  danheck: https://danheck.github.com/drat/

cache: packages

warnings_are_errors: true

r_packages:
  - knitr
  - rmarkdown

addons:
  apt:
    packages:
    - glpk-utils

notifications:
  email: false

before_install:
  - sudo apt-get install -y glpk
  - sudo apt-get update
