language: r
latex: true
sudo: false

warnings_are_errors: TRUE
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

r:
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org
  danheck: https://danheck.github.io/drat/

cache:
  - packages
  - ccache

env:
  - _R_CHECK_FORCE_SUGGESTS_=true
    _R_CHECK_CRAN_INCOMING_=true

r_packages:
  - Rglpk
  - Rcpp
  - quadprog
  - coda
  - knitr
  - rmarkdown


notifications:
  email: false

addons:
  apt:
    packages:
    - libglpk-dev
    - glpk-utils

before_install:
  - sudo apt-get update

after_success:
    - Rscript -e 'covr::codecov()'

