language: r

sudo: true

r:
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org
  danheck: https://danheck.github.com/drat/

cache: packages

warnings_are_errors: true

r_packages:
  - knitr
  - rmarkdown


notifications:
  email: false


before_install:
  - sudo apt-get update
