language: r

sudo: true

r:
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org
  danheck: https://danheck.github.com/drat/

cache: packages

warnings_are_errors: true

r_packages:
  - Rglpk
  - Rcpp
  - quadprog
  - coda
  - knitr
  - rmarkdown


notifications:
  email: false

addons:
  apt:
    packages:
    - libglpk-dev
    - glpk-utils

before_install:
  - sudo apt-get update

after_success:
    - Rscript -e 'covr::codecov()'

