# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adj_iterative <- function(par, c = .50, DIFF_BOUND = 0.0) {
    .Call(stratsel_adj_iterative, par, c, DIFF_BOUND)
}

