# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adj_iterative <- function(par, c = .50, DIFF_BOUND = 0.0) {
    .Call(stratsel_adj_iterative, par, c, DIFF_BOUND)
}

rbeta_trunc <- function(shape1, shape2, min, max) {
    .Call(stratsel_rbeta_trunc, shape1, shape2, min, max)
}

inside_Ab <- function(X, A, b) {
    .Call(stratsel_inside_Ab, X, A, b)
}

count_samples <- function(X, A, b) {
    .Call(stratsel_count_samples, X, A, b)
}

start_random <- function(A, b, M, start) {
    .Call(stratsel_start_random, A, b, M, start)
}

sampling_binomial_cpp <- function(k, n, A, b, prior, M, start, burnin = 5L) {
    .Call(stratsel_sampling_binomial_cpp, k, n, A, b, prior, M, start, burnin)
}

count_binomial_cpp <- function(k, n, A, b, prior, M, batch) {
    .Call(stratsel_count_binomial_cpp, k, n, A, b, prior, M, batch)
}

count_stepwise <- function(k, n, A, b, prior, M, steps, batch, start) {
    .Call(stratsel_count_stepwise, k, n, A, b, prior, M, steps, batch, start)
}

rdirichlet <- function(n, alpha) {
    .Call(stratsel_rdirichlet, n, alpha)
}

rpdirichlet <- function(n, alpha, options) {
    .Call(stratsel_rpdirichlet, n, alpha, options)
}

rpdirichlet_free <- function(n, alpha, options) {
    .Call(stratsel_rpdirichlet_free, n, alpha, options)
}

count_multinomial_cpp <- function(k, options, A, b, prior, M, batch) {
    .Call(stratsel_count_multinomial_cpp, k, options, A, b, prior, M, batch)
}

shed_options <- function(x, options) {
    .Call(stratsel_shed_options, x, options)
}

rep_options <- function(x, options) {
    .Call(stratsel_rep_options, x, options)
}

sum_options <- function(k, options) {
    .Call(stratsel_sum_options, k, options)
}

sampling_multinomial_cpp <- function(k, options, A, b, prior, M, start, burnin = 5L) {
    .Call(stratsel_sampling_multinomial_cpp, k, options, A, b, prior, M, start, burnin)
}

count_stepwise_multi <- function(k, options, A, b, prior, M, steps, batch, start) {
    .Call(stratsel_count_stepwise_multi, k, options, A, b, prior, M, steps, batch, start)
}

